name: cd

on:
  push:
    branches:
      - main

jobs:
  checkNewVersion:
    name: Check if it's a new version
    runs-on: ubuntu-latest
    outputs:
      needDeployment: ${{ steps.checkTag.outputs.exists == 'false' }}
      libVersion: ${{ env.LIB_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Retrieve version of this library
        run: |
          echo LIB_VERSION=$(grep -F -m1 "vulkanVersion=" gradle.properties | tr -d "vulkanVersion=" | tr -d "\"") >> $GITHUB_ENV

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ env.LIB_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ${{ matrix.os }}
    needs: checkNewVersion
    if: needs.checkNewVersion.outputs.needDeployment == 'true'
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build
        run: ./gradlew hostSpecificBuild

      - name: Publish
        run: ./gradlew hostSpecificPublish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  github_release:
    name: Create a github release
    runs-on: ubuntu-latest
    needs: [ checkNewVersion, publish ]
    steps:
      - name: Create github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.checkNewVersion.outputs.libVersion}}
